-- Clean slate: delete all existing sponsors
DELETE FROM sponsors;

-- Insert all 19 partners with correct data
INSERT INTO sponsors (name, logo_url, category, sub_category, bio, website, featured, tier) VALUES
('Finesser Ltd', '/images/finesser-ltd.png', 'Sponsors', 'Headline', 'Finesser is a leading branding, fashion and film production company in Nigeria, known for creating impactful visual content and curating unique fashion-forward experiences. We have worked with a diverse range of clients across industries, from music and entertainment to corporate brands, helping them tell their stories through innovative design and production. With a commitment to excellence and creativity, Finesser continues to set the standard for quality in fashion, branding, and film.', 'https://finesserltd.com', true, 'headline'),
('Finesser Ltd', '/images/finesser-ltd.png', 'Partners', 'Principal', 'Finesser is a leading branding, fashion and film production company in Nigeria, known for creating impactful visual content and curating unique fashion-forward experiences. We have worked with a diverse range of clients across industries, from music and entertainment to corporate brands, helping them tell their stories through innovative design and production. With a commitment to excellence and creativity, Finesser continues to set the standard for quality in fashion, branding, and film.', 'https://finesserltd.com', true, 'principal'),
('Sterling Bank', '/images/sterling-bank.png', 'Partners', 'Principal', 'Sterling Bank is one of Nigeria''s leading financial institutions, committed to empowering businesses and individuals through innovative banking solutions. With a strong focus on digital transformation, Sterling Bank provides seamless financial services that cater to the needs of modern customers. The bank is also dedicated to supporting Nigeria''s creative economy, fostering entrepreneurship, and driving economic growth across various sectors.', 'https://sterling.ng', true, 'principal'),
('Federal Ministry of Youth Development', '/images/federal-ministry-of-youth-development.png', 'Partners', 'Ecosystem', 'The Federal Ministry of Youth Development is responsible for formulating, implementing, and monitoring policies aimed at empowering Nigerian youths. Through various programs and initiatives, the ministry seeks to enhance youth participation in governance, entrepreneurship, and nation-building. The ministry plays a crucial role in addressing youth unemployment, promoting skills acquisition, and fostering leadership development across Nigeria.', 'https://fmyd.gov.ng', true, 'ecosystem'),
('Lagos State Government', '/images/lagos-state-government.png', 'Partners', 'Ecosystem', 'The Lagos State Government is committed to transforming Lagos into a smart, sustainable, and economically vibrant megacity. Through innovative policies and strategic investments, the government focuses on improving infrastructure, education, healthcare, and public services. Lagos continues to lead Nigeria in entrepreneurship, technology, and creative industries, making it a hub for innovation and economic growth in Africa.', 'https://lagosstate.gov.ng', true, 'ecosystem'),
('Nigerian Youth Academy', '/images/nigerian-youth-academy.png', 'Partners', 'Ecosystem', 'The Nigerian Youth Academy is dedicated to nurturing the next generation of leaders and entrepreneurs in Nigeria. Through mentorship, training, and capacity-building programs, the academy equips young Nigerians with the skills and knowledge needed to thrive in today''s competitive world. The academy focuses on leadership development, innovation, and entrepreneurship, creating pathways for youth empowerment and national development.', 'https://nigerianyouthacademy.org', true, 'ecosystem'),
('Lagos State Tourism, Arts & Culture', '/images/lagos-state-tourism-arts-and-culture.png', 'Partners', 'Ecosystem', 'The Lagos State Ministry of Tourism, Arts, and Culture is dedicated to promoting Lagos as a premier destination for tourism, arts, and cultural experiences. The ministry works to preserve Lagos'' rich cultural heritage while fostering the growth of the creative and entertainment industries. Through strategic partnerships and initiatives, the ministry aims to position Lagos as a cultural and economic powerhouse in Africa.', 'https://lagostourism.gov.ng', true, 'ecosystem'),
('Afe Babalola & Co', '/images/afe-babalola-co.png', 'Partners', 'Ecosystem', 'Afe Babalola & Co. is one of Nigeria''s most reputable law firms, known for its excellence in legal practice and commitment to justice. The firm provides a wide range of legal services, including corporate law, litigation, intellectual property, and legal advisory. With a legacy of integrity and professionalism, Afe Babalola & Co. continues to set the standard for legal excellence in Nigeria and beyond.', 'https://afebabalola.com', true, 'ecosystem'),
('Ajike People Support Centre', '/images/ajike-people-support-centre.png', 'Partners', 'Ecosystem', 'Ajike People Support Centre is a non-profit organization dedicated to empowering underserved communities in Nigeria through education, healthcare, and economic support. The organization focuses on creating sustainable solutions to poverty, inequality, and social injustice. Through various programs, Ajike works to improve the quality of life for vulnerable populations, fostering hope and opportunity for a better future.', 'https://ajikesupportcentre.org', true, 'ecosystem'),
('Aristokrat', '/images/aristokrat.png', 'Partners', 'Ecosystem', 'Aristokrat is a leading entertainment and music label in Nigeria, known for managing top artists and producing hit records that dominate the African music scene. The label has been instrumental in shaping the careers of some of Nigeria''s biggest music stars, contributing to the global rise of Afrobeats. Aristokrat continues to push the boundaries of African music and entertainment, creating opportunities for artists and fostering innovation in the industry.', 'https://aristokrat.com', true, 'ecosystem'),
('Asolar Nigeria', '/images/asolar-nigeria.png', 'Partners', 'Ecosystem', 'Asolar Nigeria is a renewable energy company committed to providing clean and affordable solar energy solutions across Nigeria. The company specializes in solar installations for homes, businesses, and communities, helping to reduce reliance on traditional power sources. With a focus on sustainability and innovation, Asolar is driving Nigeria''s transition to renewable energy and contributing to a greener future.', 'https://asolarnigeria.com', true, 'ecosystem'),
('City FM', '/images/city-fm.png', 'Partners', 'Ecosystem', 'City FM is one of Nigeria''s most popular radio stations, known for its engaging content, music, and talk shows. The station has built a loyal audience by providing quality entertainment and information that resonates with listeners across Lagos and beyond. City FM continues to be a leading voice in Nigerian media, championing youth culture, music, and community engagement.', 'https://cityfm.ng', true, 'ecosystem'),
('Emblue', '/images/emblue.png', 'Partners', 'Ecosystem', 'Emblue is a digital marketing and customer engagement platform that helps businesses connect with their customers through personalized communication. The platform offers tools for email marketing, SMS campaigns, and customer relationship management, enabling businesses to build stronger relationships with their audiences. Emblue is committed to empowering businesses with the technology they need to succeed in the digital age.', 'https://embluemail.com', true, 'ecosystem'),
('Future Africa', '/images/future-africa.png', 'Partners', 'Ecosystem', 'Future Africa is a venture capital platform focused on funding and supporting African startups and entrepreneurs. The platform provides capital, mentorship, and resources to help startups scale and succeed. Future Africa is committed to building a thriving ecosystem for African innovation, driving economic growth, and creating opportunities for the next generation of African entrepreneurs.', 'https://future.africa', true, 'ecosystem'),
('Nelson Jack Solutions', '/images/nelson-jack-solutions.png', 'Partners', 'Ecosystem', 'Nelson Jack Solutions is a leading event production and technical services company in Nigeria, specializing in stage design, sound, lighting, and visual production. With a reputation for excellence, the company has worked on some of the biggest events in Nigeria, delivering world-class production services. Nelson Jack Solutions continues to set the standard for technical excellence in the Nigerian events industry.', 'https://nelsonjack.com', true, 'ecosystem'),
('Pelham Solicitors & Advocates', '/images/pelham-solicitors-advocates.png', 'Partners', 'Ecosystem', 'Pelham Solicitors & Advocates is a leading law firm in Nigeria, providing expert legal services across various practice areas including corporate law, litigation, and intellectual property. The firm is known for its professionalism, integrity, and commitment to delivering exceptional legal solutions. Pelham Solicitors continues to be a trusted partner for businesses and individuals seeking legal expertise in Nigeria.', 'https://pelhamsolicitors.com', true, 'ecosystem'),
('Sodium Brand Solutions', '/images/sodium-brand-solutions.png', 'Partners', 'Ecosystem', 'Sodium Brand Solutions is a creative branding and marketing agency in Nigeria, specializing in brand strategy, design, and digital marketing. The agency helps businesses build strong, memorable brands that resonate with their target audiences. With a focus on creativity and innovation, Sodium Brand Solutions continues to drive success for its clients across various industries.', 'https://sodiumbrandsolutions.com', true, 'ecosystem'),
('The Plug', '/images/the-plug.png', 'Partners', 'Ecosystem', 'The Plug is Nigeria''s leading entertainment and lifestyle media platform, known for its coverage of music, fashion, culture, and events. The platform has become a go-to source for news and content that resonates with Nigeria''s youth and creative community. The Plug continues to shape conversations around African pop culture and entertainment, connecting audiences with the latest trends and stories.', 'https://theplugng.com', true, 'ecosystem'),
('Wakanow', '/images/wakanow.png', 'Partners', 'Ecosystem', 'Wakanow is Nigeria''s leading online travel agency, providing seamless booking services for flights, hotels, and travel packages. The platform has revolutionized the way Nigerians travel, making it easier and more affordable to explore the world. Wakanow is committed to providing exceptional customer service and creating memorable travel experiences for its users.', 'https://wakanow.com', true, 'ecosystem');
