-- Flutterwave Payment Gateway Integration
-- Creates payments table and updates ticket_orders for payment tracking

-- Create payments table for tracking all payment transactions
CREATE TABLE IF NOT EXISTS payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id TEXT NOT NULL,
  tx_ref TEXT NOT NULL UNIQUE,
  flw_ref TEXT,
  amount DECIMAL(10, 2) NOT NULL,
  currency TEXT NOT NULL DEFAULT 'NGN',
  status TEXT NOT NULL CHECK (status IN ('pending', 'successful', 'failed', 'cancelled')),
  payment_type TEXT,
  customer_email TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  meta JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  verified_at TIMESTAMPTZ
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_payments_order_id ON payments(order_id);
CREATE INDEX IF NOT EXISTS idx_payments_tx_ref ON payments(tx_ref);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_customer_email ON payments(customer_email);
CREATE INDEX IF NOT EXISTS idx_payments_created_at ON payments(created_at DESC);

-- Add payment tracking fields to ticket_orders table (if it exists)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'ticket_orders') THEN
    ALTER TABLE ticket_orders 
      ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded'));
    ALTER TABLE ticket_orders 
      ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;
    CREATE INDEX IF NOT EXISTS idx_ticket_orders_payment_status ON ticket_orders(payment_status);
  END IF;
END $$;

-- Add comments for documentation
COMMENT ON TABLE payments IS 'Stores all payment transactions from Flutterwave';
COMMENT ON COLUMN payments.tx_ref IS 'Unique transaction reference generated by our system';
COMMENT ON COLUMN payments.flw_ref IS 'Flutterwave transaction reference';
COMMENT ON COLUMN payments.meta IS 'Additional metadata like ticket type, quantity, etc.';
